# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    rev: v3.2.0
    hooks:
    -   id: prettier
        language: node
        name: prettier
        entry: npx prettier --write .
    -   id: eslint
        language: node
        name: eslint
        entry: npx eslint .
